### PR TITLE
10 Auto-set the Comment user

### PR DESCRIPTION
**Pull request by TheunisHattingh**

### CODE REVIEW

**Comment by christhonie** [comment]
Theunis, this is unfortunately not that easy. This was a trap to see if you tested the code, which does not work anymore.

The code, in Angular, builds a web form which has a user field. You have only removed the display of this form field. However, behind the scene there is still validation code running to make sure that the value is not null.

You will have to do the following additional steps (copy and paste from my comments to another victim):

In src\main\webapp\app\entities\comment\update\comment-update.component.ts

Verwyder die user property in die editForm. Line 29.

Verwyder die usersSharedCollection propery in die class, die userService property (wat 'n parameter in die constructor is), verwyder die import van die userService en alle ander imports wat nou nie nodig is nie, en verwyder ook die gebruik van die userService in updateForm() en loadRelationshipsOptions().

Gaan toets dan jou code en kyk of jy 'n comment kan toevoeg.

**Comment by TheunisHattingh** [comment]
Yes thanks, vir die reply. Ethan het my btjie gehelp om uit te vind wat om te remove maar sal dit weer n go gee.

________________________________

**Comment by christhonie** [comment]
@TheunisHattingh Onthou om jou issue te link aan die PR

**Review by christhonie — CHANGES_REQUESTED** [review]
Theunis, I am still waiting for your additional commits

**Review by christhonie — APPROVED** [review]
Well done Theunis. This looks super!

**Pull request merged**
